name: doa_repartos
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  confetti: 0.8.0
  http: ^1.0.0
  latlong2: 0.9.1
  flutter_map: ^8.0.0
  geolocator: 13.0.4
  audioplayers: ^6.0.0
  fl_chart: 0.68.0
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10
  file_picker: '>=8.1.2'
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  supabase_flutter: '>=1.10.0'
  connectivity_plus: ^6.1.0
  intl: ^0.19.0
  flutter_svg: ^2.0.0
  firebase_core: ^4.1.1
  shared_preferences: ^2.0.0
  webview_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/images/

# Launcher icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  remove_alpha_ios: true
  web:
    generate: true
    image_path: assets/app_icon.png
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  macos:
    generate: true
    image_path: assets/app_icon.png
  windows:
    generate: true
    image_path: assets/app_icon.png
